import { StyleSheet } from 'react-native'
import { scale } from 'react-native-size-matters/extend'

import globals from '../../../config/globals'

const styles = StyleSheet.create({
  header: {
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  headerTitle: {
    color: globals.styles.colors.colorLove,
    fontSize: scale(48),
    fontFamily: globals.fonts.secondary.style.fontFamily,
    textAlign: 'center',
    lineHeight: scale(48),
  },
  headerSubtitle: {
    // marginTop: 6,
    color: globals.styles.colors.colorBlack,
    fontSize: 26,
    fontFamily: globals.fonts.secondary.style.fontFamily,
    textAlign: 'center',
  },
  billingStarts: {
    height: 30,
    backgroundColor: 'rgba(255,255,255,0.23)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 5,
  },
  billingStartsText: {
    fontSize: 14,
    fontFamily: globals.fonts.primary.boldStyle.fontFamily,
    letterSpacing: -0.5,
    color: globals.styles.colors.colorWhite,
  },
  subscriptionButtonView: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
  },
  restoreButton: {
    ...globals.header.icons,
    width: 156,
    height: 32,
    alignSelf: 'flex-end',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: globals.styles.colors.colorBlack,
    position: 'absolute',
    top: 5,
    right: 1,
  },
  restoreButtonText: {
    fontSize: 12,
    color: globals.styles.colors.colorWhite,
  },
  pricingBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 8,
    backgroundColor: globals.styles.colors.colorWhite,
    zIndex: 3,
    height: 60,
  },
  pricingTitleBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pricingTitle: {
    fontSize: 14,
    marginLeft: 15,
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    color: globals.styles.colors.colorBlackDark,
  },
  pricingDetails: {
    justifyContent: 'flex-end',
    textAlign: 'right',
  },
  pricePerMonth: {
    color: globals.styles.colors.colorLove,
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 13,
  },
  billingAgreement: {
    padding: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: globals.styles.colors.colorWhite,
    shadowColor: globals.styles.colors.colorBlackDark,
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  billingAgreementText: {
    fontSize: 17,
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    color: globals.styles.colors.colorBlackDark,
    textAlign: 'center',
  },
  benifitsHeadline: {
    fontFamily: globals.fonts.secondary.style.fontFamily,
    lineHeight: 30,
    fontSize: 30,
    textAlign: 'center',
    color: globals.styles.colors.colorBlack,
  },
  benifitsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginTop: 16,
    marginHorizontal: 24,
  },
  benefitContainer: {
    width: '30%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  benefitTitle: {
    color: globals.styles.colors.colorLove,
    textTransform: 'uppercase',
    fontSize: 16,
    fontFamily: globals.fonts.secondary.style.fontFamily,
    textAlign: 'center',
    marginTop: 8,
  },
  termsContainer: {
    paddingHorizontal: 24,
    backgroundColor: 'transparent',
    marginVertical: 32,
  },
  termsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    alignSelf: 'flex-start',
    marginTop: 1,
    marginRight: 10,
  },
  termsColumn: {
    marginRight: 10,
    alignSelf: 'flex-start',
  },
  termsBullet: {
    color: globals.styles.colors.colorBlack,
    fontWeight: 'bold',
    lineHeight: 10,
    marginTop: 6,
  },
  termsText: {
    fontSize: 10,
    color: globals.styles.colors.colorBlack,
    marginBottom: 2,
  },
  legalContainer: {
    paddingTop: 5,
    paddingBottom: 25,
    paddingLeft: globals.window.width * 0.1,
    paddingRight: globals.window.width * 0.1,
    backgroundColor: globals.styles.colors.colorWhite,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    textAlign: 'center',
  },
  legalText: {
    color: globals.styles.colors.colorWhite,
    flexGrow: 1,
    fontSize: 12,
    flexWrap: 'wrap',
    textAlign: 'center',
  },
  legalLink: {
    color: globals.styles.colors.colorBlack,
    textDecorationLine: 'underline',
    flexGrow: 1,
    fontSize: 10,
    flexWrap: 'wrap',
    fontFamily: globals.fonts.primary.boldStyle.fontFamily,
  },
  submitContainer: {
    flexGrow: 1,
    backgroundColor: globals.styles.colors.colorWhite,
    alignItems: 'center',
    padding: 15,
    paddingTop: 0,
  },
  submit: {
    padding: 15,
    borderRadius: 35,
  },
  submitText: {
    color: globals.styles.colors.colorWhite,
    fontSize: 16,
    textAlign: 'center',
  },
  scroll: { flex: 1 },
  scrollContent: {
    marginTop: 16,
    paddingBottom: 48,
  },
  contactSupport: { marginTop: 23, marginBottom: 32 },
})

export default styles
