import { StyleSheet } from 'react-native'
import globals from '../../config/globals'

const styles = StyleSheet.create({
  modal: { margin: 0 },
  modalContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 27,
  },
  modalContainerEmpty: {
    flex: 1,
  },
  closeButton: {
    position: 'absolute',
    top: 11,
    right: 13,
  },
  backgroundClose: { flex: 1, backgroundColor: 'transparent' },
  modalContents: {
    width: '100%',
    borderRadius: 8,
    backgroundColor: globals.styles.colors.colorWhite,
    height: 439,
    paddingTop: 30,
    paddingBottom: 29,
    paddingHorizontal: 29,
    position: 'relative',
    flexDirection: 'column',
    alignItems: 'center',
  },
  modalTitle: {
    fontFamily: globals.fonts.primary.boldStyle.fontFamily,
    fontSize: 17,
    textAlign: 'center',
    letterSpacing: -0.36,
    paddingBottom: 16,
    color: 'black',
  },
  modalDescription: {
    fontFamily: globals.fonts.primary.style.fontFamily,
    fontSize: 14,
    textAlign: 'center',
    color: globals.styles.colors.colorBlack,
    maxWidth: 290,
    marginTop: 5,
    marginBottom: 8,
  },
  weekDays: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  date: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekHeader: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 12,
    textAlign: 'center',
    color: globals.styles.colors.colorGrayDark,
    marginTop: 18,
    marginBottom: 9,
  },
  weekDay: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 10,
    textAlign: 'center',
    color: globals.styles.colors.colorGrayDark,
    marginBottom: 2,
  },
  dateWrapper: {
    width: 30,
    height: 30,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: globals.styles.colors.colorGrayDark,
  },
  disabledDate: {
    backgroundColor: globals.styles.colors.colorGrayLight,
    color: globals.styles.colors.colorGrayDark,
  },
  activeDate: {
    backgroundColor: globals.styles.colors.colorPink,
  },
  dateLabel: {
    fontFamily: globals.fonts.secondary.style.fontFamily,
    fontSize: 14,
    textAlign: 'center',
    color: globals.styles.colors.colorWhite,
  },
  disabledDateLabel: {
    color: globals.styles.colors.colorGrayDark,
  },
  modalButton: {
    width: '100%',
    height: 55,
    borderRadius: 8,
    backgroundColor: globals.styles.colors.colorPink,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
  },
  modalButtonText: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 22,
    letterSpacing: -0.39,
    color: globals.styles.colors.colorWhite,
  },
  alertBox: {
    marginTop: 46,
    width: globals.window.width,
    height: 78,
    backgroundColor: globals.styles.colors.colorWhite,
    paddingTop: 14,
    paddingRight: 33,
    paddingBottom: 14,
    paddingLeft: 31,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 1,
    shadowOffset: { width: 0, height: 4 },
    shadowColor: 'black',
    shadowOpacity: 0.15,
    shadowRadius: 18,
  },
  alertMsgs: {
    flex: 1,
    marginLeft: 23,
  },
  alert: {
    fontFamily: globals.fonts.primary.style.fontFamily,
    color: 'black',
    fontSize: 15,
  },
  alertBold: {
    fontFamily: globals.fonts.primary.boldStyle.fontFamily,
    color: 'black',
    fontSize: 15,
  },
})

export default styles
