import { StyleSheet } from 'react-native'
import globals from '../../../../config/globals'

const styles = StyleSheet.create({
  homeContainer: {
    width: globals.window.width,
    flex: 1,
  },
  foodImg: {
    marginTop: 11,
    width: '100%',
    height: 114,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  foodTitle: {
    fontFamily: globals.fonts.secondary.style.fontFamily,
    fontSize: 35,
    color: globals.styles.colors.colorBlack,
    marginTop: 27,
    marginLeft: 27,
  },
  foodType: {
    fontFamily: globals.fonts.primary.style.fontFamily,
    fontSize: 13,
    color: globals.styles.colors.colorGrayDark,
    marginTop: -5,
    marginLeft: 27,
  },
  selectContainer: {
    width: '100%',
    // borderWidth: 2,
    marginTop: 24,
    paddingHorizontal: 27,
    // height: 35,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectContainerColumn: { flexDirection: 'column', flex: 1, marginRight: 4 },
  servingSize: { fontFamily: globals.fonts.primary.boldStyle.fontFamily, fontSize: 12, color: globals.styles.colors.colorBlack },
  showPickerButton: {
    flexDirection: 'row',
    paddingHorizontal: 11,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 5,
    borderWidth: 1,
    height: 35,
    borderRadius: 3,
    borderStyle: 'solid',
    borderColor: globals.styles.colors.colorGray,
  },
  amountSelection: {
    width: 87,
    // height: '100%',
    borderRadius: 22.5,
    borderWidth: 1,
    borderColor: globals.styles.colors.colorGray,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginRight: 14,
  },
  amountText: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 14,
    color: globals.styles.colors.colorBlack,
  },
  servingSelection: {
    flex: 1,
    // height: 100,
  },
  servingSelectionColumn: { flexDirection: 'column', flex: 1, marginLeft: 4 },
  servingNumber: { fontFamily: globals.fonts.primary.boldStyle.fontFamily, fontSize: 12, color: globals.styles.colors.colorBlack },
  textInput: {
    paddingHorizontal: 11,
    marginTop: 5,
    borderWidth: 1,
    color: globals.styles.colors.colorBlackDark,
    height: 35,
    borderRadius: 3,
    borderStyle: 'solid',
    borderColor: globals.styles.colors.colorGray,
  },
  nutritionFactsHeader: {
    marginTop: 28,
    height: 35,
    width: '100%',
    backgroundColor: globals.styles.colors.colorGrayLight,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: globals.styles.colors.colorGray,
  },
  nutritionHeaderText: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 14,
    color: globals.styles.colors.colorBlack,
    textAlign: 'center',
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    zIndex: 10,
  },
  buttonContainerView: { marginTop: 30, marginBottom: 35, height: 55, paddingHorizontal: 27 },
  imageThumb: { width: 114, height: 114 },
  addFoodBtn: {
    width: '100%',
    height: '100%',
    backgroundColor: globals.styles.colors.colorPink,
    borderRadius: 35,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: globals.styles.colors.colorPink,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.71,
    shadowRadius: 10,
    elevation: 2,
  },
  buttonText: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 16,
    lineHeight: 22,
    color: globals.styles.colors.colorWhite,
    textAlign: 'center',
  },
})

export default styles
