import { StyleSheet, PixelRatio } from 'react-native'
import globals from '../../../../config/globals'

const styles = StyleSheet.create({
  close: {
    position: 'absolute',
    zIndex: 10,
    right: 12,
    top: 46,
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleLabel: {
    fontFamily: globals.fonts.secondary.style.fontFamily,
    textAlign: 'center',
    fontSize: 16,
    color: globals.styles.colors.colorWhite,
    marginTop: 52,
  },
  feelLabel: {
    fontFamily: globals.fonts.secondary.style.fontFamily,
    textAlign: 'center',
    fontSize: 20,
    color: globals.styles.colors.colorWhite,
  },
  activity: {
    marginTop: 20,
    shadowOpacity: 0.3,
    shadowRadius: 14,
    shadowColor: 'black',
    shadowOffset: { height: 2, width: 0 },
    elevation: 3,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    alignSelf: 'stretch',
    backgroundColor: globals.styles.colors.colorWhite,
  },
  activityContainer: {
    marginTop: 10,
  },
  mainMoodLabelContainer: {
    position: 'absolute',
    right: 0,
    top: -20,
    alignItems: 'center',
    width: '100%',
    zIndex: 20,
  },
  mainMoodLabel: {
    height: 48,
    paddingHorizontal: 16,
    paddingVertical: 4,
    fontFamily: globals.fonts.secondary.style.fontFamily,
    fontSize: 37,
    color: globals.styles.colors.colorBlack,
    backgroundColor: globals.styles.colors.colorGrayLight,
    borderRadius: 3,
    overflow: 'hidden',
  },
  activityTitle: {
    borderTopWidth: 1,
    borderColor: globals.styles.colors.colorGrayLight,
    fontFamily: globals.fonts.secondary.style.fontFamily,
    textAlign: 'left',
    fontSize: 23,
    color: globals.styles.colors.colorBlack,
    paddingLeft: 31,
    paddingTop: 24,
    paddingBottom: 12,
  },
  activityColumnWrapper: {
    justifyContent: 'space-evenly',
    paddingHorizontal: 20,
    backgroundColor: globals.styles.colors.colorWhite,
  },
  tile: {
    alignItems: 'center',
    width: globals.window.width * 0.25,
    height: 117,
    marginRight: 0,
  },
  iconContainer: {
    width: globals.window.width * 0.1546, // = 64 / 414
    height: globals.window.width * 0.1546,
    borderRadius: globals.window.width * 0.0773,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedIconContainer: {
    backgroundColor: globals.styles.colors.colorPink,
  },
  unselectedIconContainer: {
    borderWidth: 2,
    borderColor: globals.styles.colors.colorGrayDark,
    backgroundColor: 'transparent',
  },
  tileText: {
    marginTop: 6,
    fontFamily: globals.fonts.secondary.style.fontFamily,
    fontSize: 16,
    textAlign: 'center',
  },
  selectedActivityText: {
    color: globals.styles.colors.colorPink,
  },
  unselectedActivityText: {
    color: globals.styles.colors.colorGrayDark,
  },
  section: {
    paddingHorizontal: 31,
    paddingTop: 21,
    borderTopWidth: 1,
    borderColor: globals.styles.colors.colorGray,
    backgroundColor: globals.styles.colors.colorWhite,
    height: 137,
  },
  sectionTitle: {
    fontFamily: globals.fonts.secondary.style.fontFamily,
    textAlign: 'left',
    fontSize: 25,
    color: globals.styles.colors.colorBlack,
    paddingBottom: 5,
  },
  input: {
    fontFamily: globals.fonts.primary.style.fontFamily,
    marginHorizontal: 0,
    padding: 0,
    fontSize: 15,
    color: globals.styles.colors.colorBlackDark,
  },
  saveButton: {
    marginTop: 12,
    marginBottom: 15,
    height: 55,
    backgroundColor: globals.styles.colors.colorPink,
    borderRadius: 28,
    alignSelf: 'stretch',
    justifyContent: 'center',
    elevation: 2,
    shadowOffset: { width: 0, height: 4 },
    shadowColor: globals.styles.colors.colorPink,
    shadowOpacity: 0.5,
    shadowRadius: 5,
  },
  saveButtonText: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 16,
    letterSpacing: -0.34,
    color: globals.styles.colors.colorWhite,
    textAlign: 'center',
  },
})

export default styles
