import { StyleSheet } from 'react-native'
import globals from '../../../../config/globals'

const styles = StyleSheet.create({
  header: {
    width: globals.window.width,
    flexDirection: 'column',
    paddingBottom: 18,
  },
  expandedHeader: {
    // marginTop: Platform.OS === 'ios' ? 60 : 60 + StatusBar.currentHeight,
    // flexGrow: 0,
    // height: 163,
    paddingBottom: 12,
  },
  titleBar: {
    position: 'relative',
    height: 88,
    width: globals.window.width,
    paddingLeft: 16,
    paddingRight: 16,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  backIcon: {
    ...globals.header.icons,
    position: 'absolute',
    top: 60,
    padding: 10,
    zIndex: 10,
  },
  headerTitle: {
    fontSize: 16,
    color: globals.styles.colors.colorWhite,
    lineHeight: 22,
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    textAlign: 'center',
  },
  headerDate: {
    fontSize: 25,
    color: globals.styles.colors.colorWhite,
    fontFamily: globals.fonts.secondary.style.fontFamily,
    textAlign: 'center',
    width: '100%',
    marginTop: 7,
    marginBottom: 10,
  },
  container: {
    width: globals.window.width,
    flexGrow: 1,
  },
  row: {
    width: globals.window.width,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: globals.styles.colors.colorWhite,
  },
  activeDayButton: {
    backgroundColor: globals.styles.colors.colorWhite,
  },
  inactiveDayButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: globals.styles.colors.colorWhite,
  },
  dayWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayContainer: {
    width: 34,
    height: 34,
    borderRadius: 17,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 6,
    marginLeft: 12,
    marginRight: 12,
    marginBottom: 9,
  },
  dateWord: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 11,
    color: globals.styles.colors.colorWhite,
  },
  dayWord: {
    fontSize: 11,
    fontFamily: globals.fonts.primary.boldStyle.fontFamily,
    color: 'white',
  },
  activeDayLabel: {
    color: globals.styles.colors.colorPink,
  },
  groceryContainer: {
    flexGrow: 1,
    paddingBottom: 100,
  },
  groceryContainerList: {
    flex: 1,
  },
  noShoppingItems: {
    fontFamily: globals.fonts.primary.boldStyle.fontFamily,
    fontSize: 16,
    textAlign: 'center',
    color: globals.styles.colors.colorBlack,
  },
  buttonContainer: {
    width: '100%',
    paddingHorizontal: 27,
    height: 55,
    marginTop: 23,
  },
  createBtn: {
    width: '100%',
    height: '100%',
    backgroundColor: globals.styles.colors.colorPink,
    borderRadius: 35,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: globals.styles.colors.colorPink,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.71,
    shadowRadius: 10,
    elevation: 1,
  },
  buttonText: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.39,
    color: globals.styles.colors.colorWhite,
    textAlign: 'center',
  },
  groceryListHeader: {
    backgroundColor: globals.styles.colors.colorWhite,
    borderBottomWidth: 2,
    borderBottomColor: globals.styles.colors.colorGray,
    paddingTop: 16,
    paddingBottom: 16,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  groceryListHeaderText: {
    textAlign: 'center',
    fontSize: 12,
  },
  groceryItem: {
    height: 62,
    backgroundColor: globals.styles.colors.colorWhite,
    borderBottomWidth: 1,
    borderBottomColor: globals.styles.colors.colorGray,
    paddingTop: 11,
    paddingBottom: 10,
    paddingHorizontal: 27,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  groceryItemInfoWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  groceryItemImg: {
    width: 40,
    height: 40,
    marginRight: 14,
  },
  groceryItemInfo: {
    flex: 1,
  },
  groceryItemName: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 14,
    color: globals.styles.colors.colorBlackDark,
  },
  groceryItemQuantity: {
    fontFamily: globals.fonts.primary.semiboldStyle.fontFamily,
    fontSize: 12,
    color: globals.styles.colors.colorGrayDark,
  },
  groceryItemCheck: {
    width: 50,
    height: 50,
    marginLeft: 20,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  groceryItemUnchecked: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: globals.styles.colors.colorGray,
  },
  deleteContainer: {
    width: 73,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  delete: {
    fontSize: 30,
    color: globals.styles.colors.colorWhite,
    textAlign: 'center',
  },
  category: {
    borderRadius: 18.5,
    borderColor: globals.styles.colors.colorWhite,
    borderWidth: 1,
    paddingHorizontal: 22.5,
    paddingVertical: 8,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 5,
  },
  categoryTitle: {
    fontFamily: globals.fonts.secondary.style.fontFamily,
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 20,
    color: globals.styles.colors.colorWhite,
    textTransform: 'uppercase',
  },
  selectedCategory: {
    backgroundColor: globals.styles.colors.colorWhite,
  },
  selectedCategoryTitle: {
    color: globals.styles.colors.colorLavender,
  },
})

export default styles
